export const pricingData = [
  {
    plan: "Basic",
    price: { monthly: 0, annual: 0 },
    interval: "/month",
    description: "Perfect for beginners getting started with crypto trading.",
    buttonText: "Get Started",
    buttonType: "primary-dark",
    features: [
      "Access to 20+ cryptocurrencies",
      "Basic charting tools",
      "Market data with 15-min delay",
      "Email support",
      "Mobile app access",
    ],
    isPopular: false,
  },
  {
    plan: "Pro",
    price: { monthly: 19, annual: 15 },
    interval: "/month",
    description: "Designed for active traders seeking advanced tools.",
    buttonText: "Start 7-Day Free Trial",
    buttonType: "highlight",
    features: [
      "Access to 50+ cryptocurrencies",
      "Advanced charting tools",
      "Real-time market data",
      "Priority email support",
      "Reduced trading fees (0.1%)",
      "API access",
      "Portfolio analytics",
    ],
    isPopular: true,
  },
  {
    plan: "Enterprise",
    price: { monthly: 49, annual: 39 },
    interval: "/month",
    description: "Comprehensive solution for professional traders.",
    buttonText: "Contact Sales",
    buttonType: "primary-dark",
    features: [
      "Access to all cryptocurrencies",
      "Professional-grade charts",
      "Real-time market data",
      "24/7 dedicated support",
      "Zero trading fees",
      "Advanced API access",
      "Institutional-grade security",
      "Custom reporting",
      "Team management",
    ],
    isPopular: false,
  },
];
